Setting up API Endpoint for Analysis Results From Database
ADORSYS-GIS/report-sscrap pull request #108
Opened 2023-11-30 13:03 UTC by forkimenjeckayang

Created an API endpoint route in app.py called "/api/fetch-data", when route is accessed , it executes a function called "fetch_data_from_database" found in the apiendpoint.py file. The results gotten from the database are displayed in a tabular form using the html template file called "table_template.html"

2023-11-30 14:08 UTC, stephane-segning requested changes
Very good job Forkim! You're still missing some points

2023-11-30 14:08 UTC, stephane-segning commented on apiendpoint.py
This should come from the people implementing the database read and write.

2023-11-30 14:32 UTC, forkimenjeckayang commented on apiendpoint.py
Thank you Sir. So i should remove the apiendpoint.py file , stage and commit the changes ?

2023-11-30 17:00 UTC, stephane-segning commented on apiendpoint.py
No, you should cancel the changes done there. I mean, are you the one implementing that feature?

2023-11-30 19:08 UTC, forkimenjeckayang commented on apiendpoint.py
Yes Sir, i believe so. The interface to display charts is quite different from the one to fetch analysis results from database which is the index.html file. When fetch results button is clicked it should access the API endpoint route get contents of the database and serve to the front end.

2023-11-30 19:16 UTC, forkimenjeckayang commented
The "apiendpoint.py" file carries the logic to fetch analysis results from database when the "/api/fetch-data" route is accessed

2023-12-02 07:44 UTC, forkimenjeckayang commented
Good morning Sir @stephane-segning , changes made on file as requested. If there's any other thing to do you can let me know

2023-12-02 10:09 UTC, stephane-segning approved these changes

2023-12-02 10:09 UTC, stephane-segning commented
Good work @forkimenjeckayang

2023-12-02 10:36 UTC, merged