implementation of the start analysis button on frontend
ADORSYS-GIS/report-sscrap pull request #61
Opened 2023-11-18 10:57 UTC by Arielpetit

Done by @Arielpetit  and @Calebasah

2023-11-19 20:55 UTC, Arielpetit commented
hello sir please review our ticket

2023-11-20 10:31 UTC, stephane-segning requested changes
Very goo dcode, @Arielpetit & @Calebasah. Review these points, please:

2023-11-20 10:31 UTC, stephane-segning commented on templates/results.html
Make this match with the `base.html` file, so that no code repeat

2023-11-20 11:09 UTC, Calebasah commented on templates/results.html
> Make this match with the `base.html` file, so that no code repeat

Sir the update was done as suggested

2023-11-20 11:24 UTC, stephane-segning commented on templates/results.html
Good job @Calebasah. Now add the script link to the `base.html`

2023-11-20 11:36 UTC, stephane-segning requested changes

2023-11-20 11:36 UTC, stephane-segning commented on app.py
Why are you changing the port?

2023-11-20 12:12 UTC, Calebasah commented on app.py
The port was not responding, but the port has been updated

2023-11-21 09:23 UTC, stephane-segning approved these changes

2023-11-21 09:44 UTC, merged