Created Data Storage Functionality
ADORSYS-GIS/report-sscrap pull request #63
Opened 2023-11-18 15:24 UTC by forkimenjeckayang

Created a CSV data storage format such that when information is extracted or scrapped, it is stored in an organised manner in a specified CSV file which can later be used for analysis. Did this with @bryandino673

2023-11-18 17:17 UTC, bryandino673 commented
Sava

On Sat, Nov 18, 2023, 4:24 PM forkimenjeckayang ***@***.***>
wrote:

> Created a CSV data storage format such that when information is extracted
> or scrapped, it is stored in an organised manner in a specified CSV file
> which can later be used for analysis. Did this with @bryandino673
> <https://github.com/bryandino673>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/ADORSYS-GIS/report-sscrap/pull/63
> Commit Summary
>
>    - 922cfb9
>    <https://github.com/ADORSYS-GIS/report-sscrap/pull/63/commits/922cfb9b38100487a411735c7ed540d2f32430d3>
>    Data_format(sscrapy.py: this .py file contains scrapping logic and data
>    storing format)
>    - 1960dc1
>    <https://github.com/ADORSYS-GIS/report-sscrap/pull/63/commits/1960dc117ac7dd4139bd40b9d85282b152471634>
>    Modification(app.py: added a new route to scrape extracted data and store
>    in csv format)
>
> File Changes
>
> (2 files <https://github.com/ADORSYS-GIS/report-sscrap/pull/63/files>)
>
>    - *M* app.py
>    <https://github.com/ADORSYS-GIS/report-sscrap/pull/63/files#diff-568470d013cd12e4f388206520da39ab9a4e4c3c6b95846cbc281abc1ba3c959>
>    (10)
>    - *A* sscrapy.py
>    <https://github.com/ADORSYS-GIS/report-sscrap/pull/63/files#diff-deb70309fa60a454fef23b01ee2a5007b483e0a8770d995a6e38e56e33f35c96>
>    (22)
>
> Patch Links:
>
>    - https://github.com/ADORSYS-GIS/report-sscrap/pull/63.patch
>    - https://github.com/ADORSYS-GIS/report-sscrap/pull/63.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ADORSYS-GIS/report-sscrap/pull/63>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BDU7MZ45YLXAEWWNKTIHZZ3YFDHKNAVCNFSM6AAAAAA7RBKS6GVHI2DSMVQWIX3LMV43ASLTON2WKOZSGAYDANBWGQZTANY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-11-20 10:35 UTC, stephane-segning requested changes
This ticket is all about documentation, not coding. Document the storage only, then implement it in the next ticket.

2023-11-20 12:20 UTC, forkimenjeckayang commented
Changes made as requested Sir. Please have a review and let me know if all is good now.

2023-11-20 13:03 UTC, stephane-segning requested changes
Cancel changes that were made here

2023-11-20 13:03 UTC, stephane-segning commented on app.py
Why are there changes here?

2023-11-20 13:08 UTC, forkimenjeckayang commented on app.py
i made changes to app.py and added the sscrapy.py file too. Since this ticket was all about documentation i had to remove sscrapy.py file and also remove the code i put in app.py

2023-11-20 13:23 UTC, stephane-segning requested changes

2023-11-20 13:23 UTC, stephane-segning commented on app.py
Then cancel the changes that are here too then. Only keep the doc

2023-11-20 13:57 UTC, bryandino673 commented
sir the changes have been removed

2023-11-20 16:04 UTC, stephane-segning approved these changes
Good work!

2023-11-21 07:25 UTC, merged