53 design the user interface for input
ADORSYS-GIS/report-sscrap pull request #74
Opened 2023-11-20 12:07 UTC by ndefokou

@stephane-segning

2023-11-20 13:04 UTC, stephane-segning requested changes
Good job. Just this small part remains

2023-11-20 13:04 UTC, stephane-segning commented on templates/input.html
Cancel changes that were made here.

2023-11-20 13:08 UTC, stephane-segning commented
Please link a ticket

2023-11-21 14:10 UTC, nancymuyeh commented
@stephane-segning merge conflict resolved

2023-11-21 15:38 UTC, stephane-segning approved these changes
Good work @ndefokou @nancymuyeh !

2023-11-21 16:07 UTC, merged