Implementing the Input Interface for inputing a list of websites
ADORSYS-GIS/report-sscrap pull request #75
Opened 2023-11-20 13:10 UTC by Blindspot22

2023-11-20 14:03 UTC, Christiantyemele commented
please sir you close our ticket without us making a pull request

2023-11-20 16:09 UTC, stephane-segning commented
> please sir you close our ticket without us making a pull request 

Where is your pull request @Christiantyemele? Please past the link of it after this comment.

2023-11-20 16:36 UTC, Christiantyemele commented
the issues is that you closed and merge our ticket without us(Scott and i)  even making a pull request

2023-11-21 10:28 UTC, Blindspot22 commented
We will then do another pull request

2023-11-21 13:23 UTC, Christiantyemele commented
@stephane-segning resolved merge conflicts

2023-11-21 17:26 UTC, stephane-segning requested changes
Please remove the `.idea` folder and exclude it using `.gitignore`

2023-11-22 07:18 UTC, Christiantyemele commented
@stephane-segning  .idea folder placed in the .gitignore file

2023-11-24 10:40 UTC, Christiantyemele commented
@stephane-segning  modified the input.html file to meet the new specificities

2023-11-25 11:38 UTC, Christiantyemele commented
@stephane-segning requesting a review to approve merging

2023-11-25 21:19 UTC, stephane-segning requested changes
Please check this

2023-11-25 21:19 UTC, stephane-segning commented on docs/input-field.md
Why did you deleted this file? Please cancel this change

2023-11-27 08:19 UTC, Christiantyemele commented
@stephane-segning sir  i did not remove docs/input-field.md

2023-11-29 09:23 UTC, Awambeng requested changes

2023-11-29 09:23 UTC, Awambeng commented on templates/input.html
Hello guys, you did a good job but i think there are some slight changes to review. When i tested your interface i noticed the following:
- The input and depth of scrapping field text are white making the user not seeing what he or she types
- Finally, the user should scrape both images and number of text not asking he or she to choose an option

2023-11-29 09:40 UTC, Blindspot22 commented on templates/input.html
Ok just give me a sec

2023-11-29 15:52 UTC, Blindspot22 commented on templates/input.html
@stephane-segning and @Awambeng  Please review the new modifications

2023-11-30 10:14 UTC, Awambeng approved these changes
Code verified and confirmed @stephane-segning you have the final say.

2023-11-30 10:19 UTC, stephane-segning commented
Thank you @Awambeng. But please @Blindspot22, remove changes that are not yours

2023-11-30 10:27 UTC, Blindspot22 commented
Thank you @stephane-segning and @Awambeng Hope all is good apart from the changes that have to be removed ???

2023-11-30 11:05 UTC, stephane-segning commented
@Blindspot22 I can see unrelated changes here:
<img width="591" alt="Screenshot 2023-11-30 at 12 04 02" src="https://github.com/ADORSYS-GIS/report-sscrap/assets/26783557/4a39c5db-3a94-4ce2-af5f-2571761c55ba">

and here:
<img width="298" alt="Screenshot 2023-11-30 at 12 04 48" src="https://github.com/ADORSYS-GIS/report-sscrap/assets/26783557/59d2df88-07e9-4e05-a8dd-70a9a645d833">

and here too
<img width="368" alt="Screenshot 2023-11-30 at 12 05 04" src="https://github.com/ADORSYS-GIS/report-sscrap/assets/26783557/f2487213-5dd2-48a0-8164-988242725d7b">

Ask @Awambeng how to cancel changes that are not related

2023-11-30 15:38 UTC, Christiantyemele commented
@stephane-segning  i confirm the code in the PR is same as the local repository

2023-11-30 15:56 UTC, stephane-segning approved these changes
Good work @Awambeng @Blindspot22 @Christiantyemele ! This was a difficult one :)

2023-11-30 16:01 UTC, merged