48 testing data saving functionality
ADORSYS-GIS/report-sscrap pull request #78
Opened 2023-11-20 21:53 UTC by mbunwe-victor

Writing a unit test for the data functionality and an end-to-end test  to ensure the data scraped is accurately saved in a file.

2023-11-28 07:34 UTC, stephane-segning requested changes
I cannot approve this PR, if the related dependencies (#47) are not done

2023-11-30 10:04 UTC, stephane-segning requested changes
Please cancel unrequired changes

2023-11-30 10:04 UTC, stephane-segning commented on .gitignore
This change is not good for your ticket. Please cancel it

2023-11-30 10:04 UTC, stephane-segning commented on error_handling.py
This change is not good for your ticket. Please cancel it

2023-11-30 10:04 UTC, stephane-segning commented on test_end_to_end.py
This change is not good for your ticket. Please cancel it

2023-11-30 10:04 UTC, stephane-segning commented on validation.py
This change is not good for your ticket. Please cancel it

2023-11-30 10:58 UTC, mbunwe-victor commented
sir @stephane-segning  i have removed the changes

2023-11-30 11:02 UTC, stephane-segning approved these changes

2023-11-30 11:11 UTC, merged