feature #39 backend:Integrate analysis script with backend API
ADORSYS-GIS/report-sscrap pull request #90
Opened 2023-11-27 05:24 UTC by nancymuyeh

2023-11-27 21:47 UTC, Bansikah commented
@stephane-segning feature(backend) integrate analysis script with backend API by @nancymuyeh & @Bansikah

2023-11-28 07:32 UTC, stephane-segning requested changes
Good work guys! But still a problem, at least for me. This ticket is where you bind
- #38 with
- #34 

as explained here #39. So normally you're not done yet, if those are not done. Plus, your code contains changes that are not coming from you. You probably didn't pulled changes from the main branch before adding your changes

2023-11-28 07:32 UTC, stephane-segning commented on templates/test.html
What is the purpose of this file for this ticket please?

2023-11-28 07:32 UTC, stephane-segning commented on .gitignore
What is the purpose of this file for this ticket please?

2023-11-28 07:32 UTC, stephane-segning commented on analysis.py
What is the purpose of this file for this ticket please?

2023-11-28 07:32 UTC, stephane-segning commented on analyze.ipynb
What is the purpose of this file for this ticket please?

2023-11-28 07:32 UTC, stephane-segning commented on doc/38-implement-data-analysis-script.md
What is the purpose of this file for this ticket please?

2023-11-28 07:32 UTC, stephane-segning commented on templates/base.html
What is the purpose of this file for this ticket please?

2023-11-28 07:32 UTC, stephane-segning commented on templates/results.html
What is the purpose of this file for this ticket please?

2023-11-28 07:32 UTC, stephane-segning commented on templates/input.html
Please remove changes that are not yours

2023-11-28 07:32 UTC, stephane-segning commented on app.py
This file seems outdated or contain changes that are not yours. Please fix this

2023-11-28 15:31 UTC, Bansikah commented
@stephane-segning Removed files(global) removed files not needed

2023-11-28 16:39 UTC, stephane-segning requested changes
You didn't reviewed my points. Please, cancel changes that are not related to your ticket.

2023-11-28 16:39 UTC, stephane-segning commented on .gitignore
Cancel the change in this file

2023-11-28 16:39 UTC, stephane-segning commented on app.py
This is still not fixed

2023-11-28 16:39 UTC, stephane-segning commented on app.py
> +class AnalyzeData(Resource):
I suppose this is your main content? Put it in another file please

2023-11-28 16:39 UTC, stephane-segning commented on requirements.txt
Is is really working? Because https://pypi.org/project/chart.jsflask-bootstrap does not exist

2023-11-28 16:39 UTC, stephane-segning commented on templates/base.html
You didn't cancelled this

2023-11-28 16:39 UTC, stephane-segning commented on templates/input.html
You didn't cancelled this

2023-11-28 16:39 UTC, stephane-segning commented on templates/results.html
You didn't cancelled this

2023-11-28 16:39 UTC, stephane-segning commented on templates/test.html
You didn't cancelled this

2023-11-29 14:17 UTC, Bansikah commented
@stephane-segning [feature(backend) integrating analysis script with backend api correction
There is a file in the branch test.ipynb please you it to test the code, i will delete after the code has been reviewed

2023-11-30 13:07 UTC, Bansikah commented
@stephane-segning  resolved merge conflicts

2023-11-30 14:06 UTC, stephane-segning approved these changes
Perfect! This is an example of good code! Well done @nancymuyeh @Bansikah

2023-11-30 14:16 UTC, Bansikah commented
Thank you @stephane-segning

2023-11-30 14:19 UTC, merged